[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
/(
  \.git
  | .gitignore
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.eggs
  | venv
  | .venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[mypy]
python_version = 3.12
check_untyped_defs = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
ignore_errors = true
ignore_missing_imports = true
implicit_reexport = true
strict_optional = true
strict_equality = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true

[tool.mypy]
plugins = "mypy_django_plugin.main"
mypy_path = "./tyf"
exclude = [
    "venv",
    ".venv",
    "migrations",
]

[tool.django-stubs]
django_settings_module = "tyf.settings"
ignore_missing_model_attributes = true