[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
/(
  \.git
  | .gitignore
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.eggs
  | venv
  | .venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''