global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

# alerting:
#   alertmanagers:
#     - follow_redirects: true
#       enable_http2: true
#       scheme: http
#       timeout: 10s
#       api_version: v2
#       static_configs:
#         - targets: []

scrape_configs:
  - job_name: "prometheus"
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "djnago-server"
    scrape_interval: 10s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "node"
    scrape_interval: 10s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    scrape_interval: 10s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["cadvisor:8092"]

  - job_name: "postgres-exporter"
    scrape_interval: 10s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "redis-exporter"
    scrape_interval: 10s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "flower"
    scrape_interval: 10s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["flower:5555"]
