{
 "title": "Celery",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Celery Worker Status",
   "type": "timeseries",
   "description": "This panel shows status of celery workers. 1 = online, 0 = offline.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "flower_worker_online", "legendFormat": "{{ worker }}" }
   ]
  },
  {
   "title": "Number of Tasks Currently Executing at Worker",
   "type": "timeseries",
   "description": "This panel shows number of tasks currently executing at worker.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flower_worker_number_of_currently_executing_tasks",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Average Task Runtime at Worker",
   "type": "timeseries",
   "description": "This panel shows average task runtime at worker by worker and task name.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flower_task_runtime_seconds_sum[5m]) / rate(flower_task_runtime_seconds_count[5m])",
     "legendFormat": "{{task}}, {{worker}}"
    }
   ]
  },
  {
   "title": "Task Prefetch Time at Worker",
   "type": "timeseries",
   "description": "This panel shows task prefetch time at worker by worker and task name.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "flower_task_prefetch_time_seconds",
     "legendFormat": "{{task}}, {{worker}}"
    }
   ]
  },
  {
   "title": "Number of Tasks Prefetched At Worker",
   "type": "timeseries",
   "description": "This panel shows number of tasks prefetched at worker by task and worker name.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "flower_worker_prefetched_tasks", "legendFormat": "{{task}}, {{worker}}" }
   ]
  },
  {
   "title": "Task Success Ratio",
   "type": "timeseries",
   "description": "This panel presents average task success ratio over time by task name.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(avg_over_time(flower_events_total{type=\"task-succeeded\"}[15m])) by (task)  / sum(avg_over_time(flower_events_total{type=~\"task-failed|task-succeeded\"}[15m])) by (task)) * 100",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Task Failure Ratio",
   "type": "timeseries",
   "description": "This panel presents average task failure ratio over time by task name.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(avg_over_time(flower_events_total{type=\"task-failed\"}[15m])) by (task) / sum(avg_over_time(flower_events_total{type=~\"task-failed|task-succeeded\"}[15m])) by (task)) * 100",
     "legendFormat": "{{ task }}"
    }
   ]
  }
 ]
}