services:
  nginx:
    container_name: tyf_nginx
    build:
      context: ./../
      dockerfile: ./.docker/prod/Dockerfile.nginx.prod
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - static_files:/tyf/backend/staticfiles/
      - media_files:/tyf/backend/mediafiles/
    env_file:
      - ./prod/conf/.env.prod
    depends_on:
      backend:
        condition: service_started
    networks:
      - nginx_network

  backend:
    container_name: tyf_backend
    build:
      context: ./../
      dockerfile: ./.docker/prod/Dockerfile.backend.prod
    command: "sh /tyf/gunicorn.sh"
    volumes:
      - static_files:/tyf/backend/staticfiles/
      - media_files:/tyf/backend/mediafiles/
    expose:
      - 8080
    env_file:
      - ./prod/conf/.env.prod
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    networks:
      - backend_network
      - nginx_network

  database:
    container_name: tyf_postgres
    image: postgres:13.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
      - ./prod/conf/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    env_file:
      - ./prod/conf/.env.prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tyf_admin -d tyf"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - backend_network

  redis:
    container_name: tyf_redis
    restart: unless-stopped
    env_file:
      - ./prod/conf/.env.prod
    build:
      context: ./../
      dockerfile: ./.docker/prod/Dockerfile.redis.prod
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    expose:
      - 6379
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-server --daemonize yes && sleep 1 && redis-cli ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - backend_network

  beat:
    container_name: tyf_beat
    restart: unless-stopped
    build:
      context: ./../
      dockerfile: ./.docker/prod/Dockerfile.backend.prod
    command: "sh /tyf/celery.sh"
    env_file:
      - ./prod/conf/.env.prod
    expose:
      - 7999
    depends_on:
      - database
      - redis
      - backend
    networks:
      - backend_network

volumes:
  postgres_data_prod:
  static_files:
  media_files:

networks:
  nginx_network:
    driver: bridge
  backend_network:
    driver: bridge
